### ISSUE TITLE
Method for Text Wrapping

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/terminal_table#1]
Columns need a method to handle wrapping text, let's call it `wrap_text`. 

The function `wrap_text` should accept a string and a maximum character width. The character width can have a reasonable minimum length, say ~20 chars.

The text should break on spaces if words are greater than the minimum character width they should be hyphenated and broken after each needed hyphen.

`wrap_text` will need to return a tuple of text rows. Each row should be no greater than the maximum width. The last line can be smaller than the minimum width. 

There are some very nice algorithms for handling text wrapping, you can implement one of those or roll your own. Anything that meets the above criteria will be fine. 

Anyone interested in working on it please let me know, I'll happily offer any guidance I can.

**Comment by yemikifouly** [comment]
I am taking this.

**Comment by yemikifouly** [comment]
@sarcoma Could you clarify this sentence? "The text should break on spaces if words are greater than the minimum character width they should be hyphenated and broken after each needed hyphen."

**Comment by OrderAndCh4oS** [comment]
@yemikifouly Thanks so much, for the swift response.

That is a poorly structured sentence, sorry. I mean the text should always try to break on the nearest space to the rows character limit. If a word is too long for the character limit it should hyphenate.

*Break on spaces*:

`wrap_text("The quick brown fox jumped over the lazy dog", max_chars=20)`

`>>> ("The quick brown fox", "jumped over the", "lazy dog")`

*Hyphenate on long word*:

`wrap_text("The quick brown fox jumped over the reallyLongWordThatDoesNotFit", max_chars=20)`

`>>> ("The quick brown", "fox jumped over the", "reallyLongWordThat-", "DoesNotFit" )`

There are some fancy rules for when and how to break words with hyphenation, but really anything that works is fine.

**Comment by yemikifouly** [comment]
@sarcoma Sounds great and makes sense. And thanks for getting back to me. Will work on it.

**Comment by OrderAndCh4oS** [comment]
@yemikifouly Look forward to seeing what you come up with. Thanks so much. 

Looks like I've left out the `requirements.txt`. The project has a dependency on https://github.com/sarcoma/Python_ANSI_Colours

`pip install ansi_colours` should get it up and running.

**Comment by yemikifouly** [comment]
@sarcoma Great!... Quick question. I was looking more closely at that example you shared. 

`wrap_text("The quick brown fox jumped over the lazy dog", max_chars=20)`
`>>> ("The quick brown fox", "jumped over the", "lazy dog")`

If the `max_chars` is 20, then shouldn't the second element is the tuple be `jumped over the lazy`?

The example for the case where we have to hyphenate doesn't seem to respect the 20 chars either.

**Comment by OrderAndCh4oS** [comment]
Yeah, you're right, it should be `jumped over the lazy` by the rules I gave. 

Either is fine though, there is a rule in typography that says you shouldn't leave the last word of a block of text on a line on its own. They are called widows and orphans: https://en.wikipedia.org/wiki/Widows_and_orphans.

If you want to take that into account, please do. If not, don't worry. The main concern is keeping the text within the max char limit.

**Comment by yemikifouly** [comment]
Sounds good! I am loving this a bit more every second!

**Comment by OrderAndCh4oS** [comment]
@yemikifouly Could you let me know if you're still working on this. I only ask as someone else is interested in implementing the next piece that relies on it. No problem either way and no rush, just checking in to see.

**Comment by JaredLGillespie** [comment]
I can take this too then.

**Comment by OrderAndCh4oS** [comment]
@JaredLGillespie Yeah got for it, I'm not sure if @yemikifouly is still working on it or not. No harm either way.

**Comment by JaredLGillespie** [comment]
How would you handle non-alphabetic characters? i.e. numbers, punctuation, etc.

For example, say you had the number `10000000000` and a width of `10`. Should the output be `(1000000000-, 00)` or `(1000000000, 0)`? Also, text may not necessarily be in sentence form, so .`(o812798).,fs|` can be some text. Does that need hyphenated?

Excel and Google Docs don't have hyphenation on their text wrapping, it just wraps to the next line. Adding hyphens only seems to make sense in say a text document where the input is ideally text. Probably not a table unless it's expected it will also be filled with text.

**Comment by OrderAndCh4oS** [comment]
I'm sold, no hyphenation.

I was going to suggest a flag to toggle hyphenation, but the way it accepts parameters at the moment is a little silly. It could use a `column_options` param rather than the `column_colours` param (the same for rows). That would give it a way to accept an option for hyphenation per column, without dumping in more parameters. The single colour params for columns and rows should probably be ditched too.

For now, no hyphenation makes sense, just wrapping at the break will be fine.

Another thought has just occurred to me. If the input contains line breaks that would knock out row alignment. Existing line breaks should be preserved by removing the break moving that content to a new row tuple.
