### ISSUE TITLE
Write more robust tests

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/terminal_table#11]
Make sure the project is fully tested for all many of possible inputs and use cases. 

For example:

- Ensure sensible errors are thrown when presented with incompatible inputs.
- Find and create tests for edge cases.
- Each static function can be unit tested.

**Comment by ebarnsli** [comment]
where does this work i don't see it in any of my terminals

**Comment by OrderAndCh4oS** [comment]
@ebarnsli What is it you've tried to do? 

Have a look in the `test` directory for how to pass data to the `Table.create()` method. 

I added a little more documentation to the readme. Will fill this out some more in a bit.

To install `pip install terminal_table`

Minimal example:

```python
from terminal_table import Table

print(Table.create(((1, 2, 3), (5, 6, 7)), ('a', 'b', 'c')))
```

**Comment by ebarnsli** [comment]
Whenever i used it in the terminal i the Color separators just come out as unicode characters and not a colored `|`

**Comment by ebarnsli** [comment]
thanks for taking my tests :) i tried to knock off the smaller functions, unfortunately it was a little challenging to dig into some of the large functions. After about an hour i felt relatively familiar with your code which was a 👍 to me :)

**Comment by OrderAndCh4oS** [comment]
@ebarnsli Thanks so much, your contribution is very much appreciated. If you want to tweak anything or add any other features do feel free, ping over a PR anytime.
