### ISSUE TITLE
Handle Text Wrapping

### ISSUE THREAD

**Issue by OrderAndCh4oS** [sarcoma/terminal_table#2]
Following on from "[Function for Text Wrapping](https://github.com/sarcoma/terminal_table/issues/1)" the program will need to implement the text wrapping function `wrap_text`.

The `create` method will need to accept an optional `column_width` parameter, an integer that is greater than the minimum character limit of the `wrap_text`.

`create` and `make_row` will need to be able to handle the additional rows that wrapping text will require. The `wrap_text` function will return a tuple of rows of text.

**Comment by JaredLGillespie** [comment]
I can take a :hocho: at this.

**Comment by OrderAndCh4oS** [comment]
@JaredLGillespie Thanks so much, the `wrap_text` function does not exist yet, someone else kindly offered to take a look at it. 

Once they post up a PR I'll let you know.

**Comment by JaredLGillespie** [comment]
Should the `column_width` parameter set the width of all the columns to be that? i.e. column_width=20 so all columns have width of 20.

Or, should it be `max_column_width` (better name) where it's the maximum width a column will expand to? i.e. max_column_width=20 means columns can be up to width of 20 (can also be less than 20).

Also, how would you handle the scenario where the header is longer than the column_width? Should the headers be wrapped to the column_width? Or should the column_width be `max(column_width, len(header))`?

**Comment by OrderAndCh4oS** [comment]
@JaredLGillespie Good questions, the answer is I don't know. 

It'd be great to be able to define `max_column_width` per column. I'd imagine a tuple of `max_column_widths` could be passed in like `(20, 30, 40)`. The colours are passed in like this. 

Yes, headers should also wrap. On that note, perhaps not all columns ought to wrap, maybe passing `None` into the `max_column_widths` for a column would let it be variable (ie work as it currently does). If no tuple is passed to `max_column_widths=None` it would behave as it already does.

**Comment by JaredLGillespie** [comment]
When having cells comprised of multiple lines, it can currently be difficult to actual discern when one cell begins and another ends. 

**Example:** Assume width of 2.
```
|  a   |  b   |  c   |
|------|------|------|
|  xx  |  yy  |  zz  |
|  xx  |  y   |  zz  |
|  x   |  yy  |  zz  |
```
Are there 3 rows? 1 row with each cell wrapped each time? 2 rows with 1 of the cells wrapped once? It's kinda of hard to tell without either **A.** line numbers on the left, or **B.** dividers between cells.

**Option A:** Assume width of 2.
```
|  #  |  a   |  b   |  c   |
|-----|------|------|------|
|  1  |  xx  |  yy  |  zz  |
|     |  xx  |  y   |  zz  |
|  2  |  x   |  yy  |  zz  |
```

**Option B:** Assume width of 2.
```
|  a   |  b   |  c   |
|------|------|------|
|  xx  |  yy  |  zz  |
|  xx  |  y   |  zz  |
|------|------|------|
|  x   |  yy  |  zz  |
```

**Option A + B:** Assume width of 2.
```
|  #  |  a   |  b   |  c   |
|-----|------|------|------|
|  1  |  xx  |  yy  |  zz  |
|     |  xx  |  y   |  zz  |
|-----|------|------|------|
|  2  |  x   |  yy  |  zz  |
```

Either of these seem fine. However, it might also make sense to make these additional optional parameters that get passed in so the users can choose how to display the table. Might recommend these as a separate PR.

**Comment by OrderAndCh4oS** [comment]
Ah yes, good spot. Option B works for me.

In the pagination repo I dropped you a link to it handles assigning a key down the left-hand side for selecting a row. Though that could be ported over to this project, I do think that should be an optional column, I don't think it shouldn't be forced.

**Comment by JaredLGillespie** [comment]
I went ahead and added **Option B** in the text wrapping PR. As well as the functionality to resolve issue #1.
