### ISSUE TITLE
Automated test suite

### ISSUE THREAD

**Issue by jayvdb** [sarcoma/terminal_table#4]
It would be helpful to have an automated test suite, to check this works correctly on new versions of Python, etc.

**Comment by OrderAndCh4oS** [comment]
@jayvdb That would be awesome, are you putting yourself forward for that? I can assign it to you if you like. There are some rudimentary demos in `if __name__ == '__main__':` that'd get it started off.

**Comment by jayvdb** [comment]
They cant really be used there, as the `__main__` cant be invoked within a library.

Could you move them to a file outside the package, maybe called `tests.py`.

Then I could run them, and move this library to 'visual tests only' in my summary at https://github.com/dephell/dephell/issues/206#issuecomment-543760331

**Comment by OrderAndCh4oS** [comment]
@jayvdb I'll write some tests now. Are there any particular features that project is looking for that 
could use a specific test case?

There is also a partner project for these tables: https://github.com/sarcoma/Terminal-Pagination (No tests either though). I plan to get that working with API calls at some point. At the moment it can be passed a list. If that's of any interest I can get to work on that.

**Comment by OrderAndCh4oS** [comment]
@jayvdb I've moved the basic visual tests to a pytest testing suite.  Now looking into how to automate the tests.

Once it's automated I'll add some more test cases.

**Comment by OrderAndCh4oS** [comment]
@jayvdb Tests are now run CircleCI upon success it'll build and deploy a new package.
